// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcmmiphcftqvfgojhnfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbW1pcGhjZnRxdmZnb2pobmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTIwMTYsImV4cCI6MjA2Mjc4ODAxNn0.DcaA-zQQvBGz4_ySQkIxwzlz6DVd38oZWgg4Xay78uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);